import { jsPDF } from "jspdf";
import { TripPlan } from "../types";

export function exportTripToPDF(trip: TripPlan): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header banner background
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 40, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("TripGenius AI Travel Itinerary", 14, 22);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(226, 232, 240);
  doc.text(`${trip.title} (${trip.preferences.duration} Days in ${trip.destination}, ${trip.country})`, 14, 32);

  y = 50;

  // Overview box
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Trip Summary & Details", 14, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);

  const summaryLines = doc.splitTextToSize(trip.summary, pageWidth - 28);
  doc.text(summaryLines, 14, y);
  y += summaryLines.length * 5 + 5;

  // Key Stats Table
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, y, pageWidth - 28, 24, 2, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.text("Estimated Budget:", 18, y + 8);
  doc.setFont("helvetica", "normal");
  doc.text(`${trip.currency}${trip.totalBudgetEstimated}`, 55, y + 8);

  doc.setFont("helvetica", "bold");
  doc.text("Travel Type:", 110, y + 8);
  doc.setFont("helvetica", "normal");
  doc.text(`${trip.preferences.travelType}`, 135, y + 8);

  doc.setFont("helvetica", "bold");
  doc.text("Official Language:", 18, y + 17);
  doc.setFont("helvetica", "normal");
  doc.text(`${trip.language}`, 55, y + 17);

  doc.setFont("helvetica", "bold");
  doc.text("Best Season:", 110, y + 17);
  doc.setFont("helvetica", "normal");
  doc.text(`${trip.bestTimeToVisit}`, 135, y + 17);

  y += 32;

  // Budget Breakdown
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Budget Breakdown", 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  trip.budgetBreakdown.forEach((b) => {
    doc.text(`• ${b.category}: ${trip.currency}${b.amount} (${b.percentage}%) - ${b.description}`, 18, y);
    y += 5;
  });

  y += 6;

  // Daily Schedule
  if (y > 230) {
    doc.addPage();
    y = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Daily Schedule", 14, y);
  y += 8;

  trip.dailyItinerary.forEach((day) => {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(238, 242, 255);
    doc.rect(14, y, pageWidth - 28, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(67, 56, 202);
    doc.text(`Day ${day.dayNumber}: ${day.theme}`, 18, y + 5);
    y += 11;

    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);

    if (day.morning) {
      doc.setFont("helvetica", "bold");
      doc.text("Morning:", 18, y);
      doc.setFont("helvetica", "normal");
      const mText = doc.splitTextToSize(`${day.morning.title} - ${day.morning.description}`, pageWidth - 45);
      doc.text(mText, 38, y);
      y += mText.length * 4.5 + 2;
    }

    if (day.afternoon) {
      doc.setFont("helvetica", "bold");
      doc.text("Afternoon:", 18, y);
      doc.setFont("helvetica", "normal");
      const aText = doc.splitTextToSize(`${day.afternoon.title} - ${day.afternoon.description}`, pageWidth - 45);
      doc.text(aText, 38, y);
      y += aText.length * 4.5 + 2;
    }

    if (day.evening) {
      doc.setFont("helvetica", "bold");
      doc.text("Evening:", 18, y);
      doc.setFont("helvetica", "normal");
      const eText = doc.splitTextToSize(`${day.evening.title} - ${day.evening.description}`, pageWidth - 45);
      doc.text(eText, 38, y);
      y += eText.length * 4.5 + 2;
    }

    y += 4;
  });

  // Footer page numbers
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by TripGenius AI – Page ${i} of ${pageCount}`, pageWidth / 2, 287, { align: "center" });
  }

  // Save file
  const fileName = `${trip.destination.toLowerCase()}_trip_itinerary.pdf`;
  doc.save(fileName);
}
